### ISSUE TITLE
gen_summary failed with IndexError

### ISSUE THREAD

**Issue by kazenokizi** [weirme/FCSN#22]
Hello @weirme ,

Thank you for the great implementation. 

I tried to use gen_summary.py to generate summaries for tvsum videos but failed. I used the default settings in the code and laid the dataset accordingly, but an IndexError is thrown. 

I found that it is because the video IDs are not used right. The IDs in the original TVSum dataset are random names, but in your case ids are 1-50. So do you have a mapping between the two? 

Thanks.

**Comment by SinDongHwan** [comment]
Hi, @kazenokizi 
I want to ask something to you.
first, could you tell me about error message?
second, Do you have a TVSum Dataset(original)?

**Comment by kazenokizi** [comment]
Hi @weirme 
Thanks for the reply. I actually poked a bit around so the error message is different now. To answer your questions:
1. The error now is cannot find the videos by id. I attach a snapshot for your info: 
![Screenshot from 2020-03-16 18-56-07](https://user-images.githubusercontent.com/8514847/76749659-d2b56200-67b7-11ea-97d2-9cd5e573d805.png)
2. I do have the original TVSum dataset, but the videos are not numbered but named with random bits: 
![Screenshot from 2020-03-16 18-57-27](https://user-images.githubusercontent.com/8514847/76749810-19a35780-67b8-11ea-87af-52351a659f30.png)

Cheers.

**Comment by SinDongHwan** [comment]
Hi, kazenokizi
Did you load a  "fcsn_tvsum.h5"?
i think you've loaded a wrong file.
you have to assign "fcsn_tvsum.h5" to h5_path.

Good Luck!

**Comment by kazenokizi** [comment]
Hi @SinDongHwan 
I actually set the h5 file path right, but the ids, which you can see in the snapshot I attached in my latest reply, are str-typed numbers. I think these should be video names, but these names on the other hand are random bits. So I guess there is a mapping between the numbered ids and the random bits. 

Cheers, and thank you for answering.

**Comment by SinDongHwan** [comment]
Hi, @kazenokizi 
I tried on python console. I'm working well. 
![FCSN_test](https://user-images.githubusercontent.com/30520896/76836264-e4f4d600-6873-11ea-8823-6194a80a5ef0.png)

**Comment by kazenokizi** [comment]
I tried but failed. So it seems like my file is corrupted. I will redownload the file. Thanks for the great help. :)
